---
title: "Fish and health with national fish promotion programme"
output:
  html_document:
    df_print: paged
---

This is an open assessment looking at potential health effects of a national fish promotion program in Finland. The details of the assessment are described on [Opasnet](http://fi.opasnet.org/fi/Kotimaisen_kalan_edistämisohjelma). This file contains the R code to run the assessment model.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 

```

Calculation is based on BONUS GOHERR project and its [http://en.opasnet.org/w/Goherr_assessment](fish health benefit-risk assessment).

```{r}

# This is code Op_fi5923/model on page [[Kotimaisen kalan edistämisohjelma]]
library(OpasnetUtils)
library(ggplot2)
library(plotly)

# First empty all objects for a fresh start. Otherwise may be problems with CheckDecisions.
oempty(all=TRUE)

openv.setN(10)

dat <- opbase.data("Op_fi5923", subset="Malliparametrit")[-1]

dec <- opbase.data("Op_fi5923", subset="Decisions")[-1]
DecisionTableParser(dec)

CTable <- opbase.data("Op_fi5923",subset="CollapseMarginals")
for(i in 1:ncol(CTable)) {CTable[[i]] <- as.character(CTable[[i]])}
CollapseTableParser(CTable)

cat("Laskennassa käytetty data.\n")
oprint(dat)
cat("Tarkastellut päätökset.\n")
oprint(dec)
cat("Aggregoidut marginaalit.\n")
oprint(CTable)

#' prepare adjusts the data table for ovariables. Requires function subgrouping from code Op_en2031/initiate on page [[Exposure-response function]]
#' @param dat data.frame
#' @param type type of data that is used. Must match content in column Type
#' @param drop columns to remove
#' @return data.frame

prepare <- function(dat, type=NULL, drop=NULL) {
  out <- dat
  if(!is.null(type)) out <- out[out$Type %in% type , ]
  if(!is.null(drop)) out <- out[!colnames(out) %in% drop]
  return(subgrouping(out))
}

objects.latest("Op_en2031", code_name="subgrouping") # [[Exposure-response function]] subgrouping

population <- Ovariable("population", data = prepare(dat,"population",c("Type","Exposure_agent","Response","Unit")))

amount <- Ovariable("amount", data = prepare(dat, "amount", c("Type","Response","Exposure_agent")))

# Exposuressa summataan Kala-sarake pois, jolloin jää vain Exposure_agent.
# Miten lisätään tieto Exposure:To child vai To eater?

conc_vit <- Ovariable(
  "conc_vit",
  ddata = "Op_en1838", # [[Concentrations of benecifial nutrients in fish#Fineli]]
  subset = "Fineli data for common fish species"
)
levels(conc_vit@data$Nutrient)[levels(conc_vit@data$Nutrient)=="D-vitamiini (µg)"] <- "Vitamin D"
levels(conc_vit@data$Nutrient)[levels(conc_vit@data$Nutrient)=="rasvahapot n-3 moni-tyydyttymättömät (g)"] <- "Omega3"
levels(conc_vit@data$Nutrient)[levels(conc_vit@data$Nutrient)=="rasvahappo 18:3 n-3 (alfalinoleenihappo) (mg)"] <- "ALA"
levels(conc_vit@data$Nutrient)[levels(conc_vit@data$Nutrient)=="rasvahappo 22:6 n-3 (DHA) (mg)"] <- "DHA"
levels(conc_vit@data$Nutrient)[levels(conc_vit@data$Nutrient)=="proteiini (g)"] <- "Fish"
conc_vit@data$conc_vitResult[conc_vit@data$Nutrient=="Fish"] <- 1
conc_vit <- conc_vit[conc_vit$Nutrient %in% c("Vitamin D", "Omega3", "ALA", "DHA", "Fish") , ]

exposure <- Ovariable(
  "exposure",
  dependencies = data.frame(Name=c("conc_vit", "amount")),
  formula = function(...) {
    
    # First, match KKE-classification with Fineli classification
    
    conc_vit$Kala <- NULL
    tmp <- Ovariable(
      output = data.frame(
        Kala = c("Kasvatettu", "Kaupallinen", "Kirjolohi", "Silakka", "Vapaa-ajan", "Muu tuonti", "Tuontikirjolohi", "Tuontilohi"),
        Fish = c("Whitefish", "Average fish","Rainbow trout", "Herring", "Average fish", "Average fish", "Rainbow trout", "Salmon"),
        Result = 1
      ))
      
    amount <- amount * 1000 / 5.52 /365.25 # M kg/a per population --> g/d per person
    out <- conc_vit * tmp * amount
    colnames(out@output)[colnames(out@output)=="Nutrient"] <- "Exposure_agent"
      
    return(out)
  },
  marginal = c(TRUE, TRUE, FALSE)
)

# frexposed <- Ovariable("frexposed", data=prepare(dat, "frexposed", c("Type","Response","Unit")))

frexposed <- 1

incidence <- Ovariable("incidence", data = prepare(dat,"incidence",c("Type","Exposure_agent","Unit")))

#ERFChoice <- Ovariable(
#  "ERFchoice",
#  data=data.frame(
#    Response=c("IQ loss","Liver cancer","Yes or no dental defect","Cancer morbidity","Sperm concenctration"),
#    Exposure_agent=c("Lead","Aflatoxin","TEQ","TEQ","TEQ"),
#    Result=1)
#)

case_burden <- Ovariable("case_burden", data= prepare(dat,"case burden",c("Type","Exposure_agent","Unit")))

#InpPAF <- EvalOutput(Ovariable("InpPAF", data =  prepare(dat,"PAF","Type")))

# InpBoD2 <- EvalOutput(Ovariable("InpBoD", data = prepare(dat, "BoD", c("Type","Exposure_agent")))) # REMOVE RUORI CHD AND USE GOHERR

objects.latest("Op_en5917", code_name="InpBoD") # [[Disease risk]] InpBoD

InpBoD <- EvalOutput(InpBoD) # Evaluated because is not a dependency but an Input
InpBoD <- InpBoD[InpBoD$Country=="FI",colnames(InpBoD@output)!="Country"]

objects.latest("Op_en2261",code_name="BoDattr2") # [[Health impact assessment]]

exposure <- EvalOutput(exposure, verbose=TRUE)

```

```{r}

BoDattr <- EvalOutput(BoDattr, verbose=TRUE)

cat("exposure\n")
oprint(summary(exposure,marginals=c("Exposure_agent","Age","Scenario")),digits=7)
oprint(exposure@output[exposure$Iter==1,])
cat("dose\n")
oprint(summary(dose),digits=7)
cat("ERF\n")
oprint(ERF@output[ERF$Iter==1,],digits=7)
cat("incidence\n")
oprint(summary(incidence),digits=7)
cat("frexposed\n")
oprint(summary(frexposed),digits=7)
cat("PAF\n")
oprint(summary(PAF),digits=7)
cat("BoD\n")
oprint(summary(BoD),digits=7)
cat("BoDattr\n")
oprint(summary(BoDattr,marginals=c("Response","Exposure_agent","Scenario","Age")),digits=7)
cat("Vähennyspotentiaali\n")
#tmp <- summary(utility, marginals=c("Exposure_agent"))
#oprint(tmp[order(unlist(tmp$mean)),])

#objects.store(list=setdiff(ls(), "wiki_username"))
#cat("Objects", setdiff(ls(), "wiki_username"), "stored.\n")

###################
# Graphs

plot_ly(data=amount@output, x=~Scenario, y=~amountResult, color=~Kala, type="bar") 

plot_ly(conc_vit@output, x=~Nutrient, y=~conc_vitResult, color=~Fish, type="scatter", mode="markers")

plot_ly(exposure@output, x=~Scenario, y=~exposureResult, color=~Exposure_agent, type="bar")

summary(conc_vit, "mean")

summary(exposure,"mean")

summary(incidence, "mean")

summary(population)



```

```{r}
BoDattr <- CollapseMarginal(BoDattr,"Threshold","sample")
utility <- CollapseMarginal(utility,"Threshold","sample")

cat("Elintarvikeperäisiä tautitaakkoja Suomessa\n")
tmp <- summary(oapply(BoDattr[BoDattr$Scenario=="BAU",],NULL,sum,c("Age","Response")))
oprint(data.frame(
  Altiste = tmp$Exposure_agent,
  Keskiarvo = signif(tmp$mean,2),
  "95 luottamusväli" = paste0(signif(tmp$Q0.025,2)," - ", signif(tmp$Q0.975,2)),
  Keskihajonta = signif(tmp$sd,2)
)[rev(match(lev, tmp$Exposure_agent)),])

cat("Ruori-skenaarioiden vaikutus tautitaakkaan\n")
tmp <- summary(utility)
oprint(data.frame(
  Altiste = tmp$Exposure_agent,
  Keskiarvo = signif(tmp$mean,2),
  "95 luottamusväli" = paste0(signif(tmp$Q0.025,2)," - ", signif(tmp$Q0.975,2)),
  Keskihajonta = signif(tmp$sd,2)
)[rev(match(lev, tmp$Exposure_agent)),])

dodge <- position_dodge(width=0.7)

ggplot(summary(oapply(BoDattr[BoDattr$Scenario=="BAU",],NULL,sum,"Age")),
       aes(x=Exposure_agent, weight=unlist(mean), fill=Response))+geom_bar()+
  theme(legend.position = "bottom")+
  labs(
   title="Elintarvikkeiden tautitaakkoja Suomessa",
   subtitle="Haittapainotettua elinvuotta vuodessa (DALY/a)")+
coord_flip()

ggplot(summary(oapply(BoDattr, NULL, sum,c("Age","Response"))),
       aes(x=Exposure_agent, weight=unlist(mean), fill=Scenario))+geom_bar(position="dodge")+
  coord_flip(ylim=c(0,70000))+
  labs(
     title="Elintarvikeperäisiä tautitaakkoja Suomessa",
     subtitle="Haittapainotettua elinvuotta vuodessa (DALY/a)")+
  geom_errorbar(aes(ymin=unlist(Q0.025),ymax=unlist(Q0.975),group=Scenario),position=dodge, width=0.3)+
  geom_text(aes(label=signif(unlist(mean),2), y=unlist(Q0.975)+5000, group=Scenario), position=dodge)

# Utility of actions

ggplot(summary(utility),aes(x=Exposure_agent, weight=unlist(mean)))+geom_bar(fill="lightblue")+
  coord_flip(ylim=c(-9000,0))+
  labs(
   title="Ruori-skenaarioiden vaikutus tautitaakkaan",
   subtitle="Haittapainotettua elinvuotta vuodessa (DALY/a)")+
  geom_errorbar(aes(ymin=unlist(Q0.025),ymax=unlist(Q0.975)), width=0.3)+
  geom_text(aes(label=signif(unlist(mean),2), y=unlist(Q0.025)-600))

################ Insight network

gr <- scrape(type="assessment")
objects.latest("Op_en3861", "makeGraph") # [[Insight network]]
gr <- makeGraph(gr)
#export_graph(gr, "ruori.svg")
render_graph(gr)

##################### Diagnostics

objects.latest("Op_en6007", code_name="diagnostics")
View(showLoctable())
View(showind())

```

